-- ═══════════════════════════════════════════════════════════════
-- Beej Setu — Migration 010: Dispatch Staff Role + Challans
--
-- Changes:
--   1. Add DISPATCH_STAFF to profiles.role constraint
--   2. Add GODOWN_DISPATCHED, TRANSPORT_DISPATCHED to orders.status
--   3. Create challans table (persists challan data)
--   4. RLS policies for challans
-- ═══════════════════════════════════════════════════════════════

-- ── Step 1: Expand profiles role constraint ───────────────────
DO $$
BEGIN
  ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
EXCEPTION
  WHEN undefined_object THEN NULL;
END;
$$;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'STAFF', 'DISPATCH_STAFF'));

-- ── Step 2: Expand orders status constraint ───────────────────
DO $$
BEGIN
  ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_status_check;
EXCEPTION
  WHEN undefined_object THEN NULL;
END;
$$;

ALTER TABLE public.orders
  ADD CONSTRAINT orders_status_check
  CHECK (status IN (
    'PENDING',
    'APPROVED',
    'PARTIALLY_APPROVED',
    'HOLD',
    'CANCELLED',
    'GODOWN_DISPATCHED',
    'TRANSPORT_DISPATCHED',
    'SHIPPED'
  ));

-- ── Step 3: Create challans table ─────────────────────────────
-- Persists the delivery challan generated by dispatch staff.
-- One challan per order (unique constraint on order_id).
CREATE TABLE IF NOT EXISTS public.challans (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id               UUID        NOT NULL UNIQUE REFERENCES public.orders(id) ON DELETE CASCADE,

  -- Challan fields filled by dispatch staff
  challan_number         TEXT        NOT NULL,
  transport_name         TEXT,
  lr_number              TEXT,

  -- Dates
  godown_dispatch_date   DATE        NOT NULL DEFAULT CURRENT_DATE,
  transport_dispatch_date DATE,

  -- Audit
  created_by             UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER challans_updated_at
  BEFORE UPDATE ON public.challans
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX idx_challans_order_id ON public.challans(order_id);

-- ── Step 4: RLS for challans ──────────────────────────────────
ALTER TABLE public.challans ENABLE ROW LEVEL SECURITY;

-- DISPATCH_STAFF, ADMIN, SUPER_ADMIN can view all challans
CREATE POLICY "challans_select"
  ON public.challans FOR SELECT
  USING (get_my_role() IN ('SUPER_ADMIN', 'ADMIN', 'DISPATCH_STAFF'));

-- DISPATCH_STAFF, ADMIN, SUPER_ADMIN can insert challans
CREATE POLICY "challans_insert"
  ON public.challans FOR INSERT
  WITH CHECK (get_my_role() IN ('SUPER_ADMIN', 'ADMIN', 'DISPATCH_STAFF'));

-- DISPATCH_STAFF, ADMIN, SUPER_ADMIN can update challans
CREATE POLICY "challans_update"
  ON public.challans FOR UPDATE
  USING (get_my_role() IN ('SUPER_ADMIN', 'ADMIN', 'DISPATCH_STAFF'));

-- Only ADMIN / SUPER_ADMIN can delete challans
CREATE POLICY "challans_delete"
  ON public.challans FOR DELETE
  USING (get_my_role() IN ('SUPER_ADMIN', 'ADMIN'));

-- ── Step 5: Allow DISPATCH_STAFF to view all orders ──────────
-- (They need to see orders from all staff members, not just their own.)
CREATE POLICY "orders_select_dispatch_staff"
  ON public.orders FOR SELECT
  USING (get_my_role() = 'DISPATCH_STAFF');

CREATE POLICY "order_items_select_dispatch_staff"
  ON public.order_items FOR SELECT
  USING (
    get_my_role() = 'DISPATCH_STAFF'
  );
